NumPy axes: https://www.sharpsightlabs.com/blog/numpy-axes-explained/

In [1]:
import numpy as np

In [2]:
# Creation and initialization
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a = np.zeros((5,6))
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
a = np.zeros((5,6,2))
a

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [56]:
# Dimensions, Size and Shape
a = np.zeros((1,224,224,3))
a.ndim


4

In [55]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
b.ndim

2

In [58]:
b.shape

(3, 3)

In [57]:
b.size

9

In [12]:
# Dataframe to Numpy
import pandas as pd
df = pd.DataFrame({"A": [0,2], "B": [1,3]})
df

A  B
0  0  1
1  2  3

In [13]:
df.to_numpy()

array([[0, 1],
       [2, 3]])

In [15]:
# Indexing and slicing
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
# Indexing
a[1][2]

6

In [17]:
# Slicing
a[0:2, 1:2]

array([[2],
       [5]])

In [23]:
# Transform
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [20]:
# Flatten
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Reshape
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
# Sum
a.sum(axis=0) # Axis 0 - rows

array([12, 15, 18])

In [27]:
a.sum(axis=1) # Axis 1 - columns

array([ 6, 15, 24])

In [28]:
a.sum() # All elements

45

In [40]:
# Addition, Subtraction, Multiplication, Dot
a = np.array([[1,-2,3], [4,5,6], [7,8,9]])
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [30]:
a + b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [31]:
a - b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
# * operator or np.multiply only multiplies corresponding elements from matrices
a * b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [36]:
# Dot product is actual matrix multiplication A X B
np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [42]:
# Inverse
a
np.linalg.inv(a)

array([[ 0.125     , -1.75      ,  1.125     ],
       [-0.25      ,  0.5       , -0.25      ],
       [ 0.125     ,  0.91666667, -0.54166667]])

$A^-1$*b*

In [46]:
np.dot(np.linalg.inv(a),b)

array([[ 1.00000000e+00,  5.00000000e-01,  8.88178420e-16],
       [-1.94289029e-16, -4.44089210e-16, -4.71844785e-16],
       [-2.22044605e-16,  5.00000000e-01,  1.00000000e+00]])

In [48]:
# Broadcasting
a = np.zeros((5,6,2))
a

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [49]:
a + 1

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [61]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
a + np.array([2,4,6])

array([[ 3,  6,  9],
       [ 6,  9, 12],
       [ 9, 12, 15]])

In [68]:
# Transforming, mapping
np.where(a == 9)

(array([2]), array([2]))

In [69]:
# vectorizing
def func(a,b):
  if a == b:
    return 0
  else:
    return a + b

vfunc = np.vectorize(func)

a = np.array([[5,2,-8,2], [2,3,6,1]])
vfunc(a, 2)

array([[ 7,  0, -6,  0],
       [ 0,  5,  8,  3]])